dist: xenial

language: php

sudo: false

php:
  - '7.2'
  - '7.3'

branches:
  only:
  - master
  - /^v?\d+\.\d+(\.\d+)?(-\S*)?$/

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: ./vendor/bin/phpunit -c ./tests/phpunit.xml

after_script:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then mv ./tests/_output/coverage-clover.xml clover.xml && ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT -t clover; fi

notifications:
  email:
    recipients:
    - nuxsmin@syspass.org
    on_success: change # default: change
    on_failure: always # default: always

cache:
  directories:
  - vendor
